DROP DATABASE IF EXISTS CSCI201_FALL2019;
CREATE DATABASE CSCI201_FALL2019;
USE CSCI201_FALL2019;

CREATE TABLE UserRegistry (
	uid INTEGER(3) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE,
    pw VARCHAR(20) NOT NULL
);

CREATE TABLE VehicleRegistry (
	vid INTEGER(3) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    details VARCHAR(100) NOT NULL UNIQUE 
);

CREATE TABLE VehicleLUT (
	uid INTEGER(3) NOT NULL,
    vid INTEGER(3) NOT NULL,
    FOREIGN KEY (uid) REFERENCES UserRegistry(uid),
    FOREIGN KEY (vid) REFERENCES VehicleRegistry(vid),
    notes VARCHAR(100)
);